export const genres = [
    // Alternative
    "Alternative",
    "Art Punk",
    "Alternative Rock",
    "Britpunk",
    "College Rock",
    "Crossover Thrash",
    "Crust Punk",
    "Emotional Hardcore",
    "Experimental Rock",
    "Folk Punk",
    "Goth",
    "Grunge",
    "Hardcore Punk",
    "Hard Rock",
    "Indie Rock",
    "Lo-fi",
    "Musique Concrète",
    "New Wave",
    "Progressive Rock",
    "Punk",
    "Shoegaze",
    "Steampunk",
    "Anime",
    // Blues
    "Blues",
    "Acoustic Blues",
    "African Blues",
    "Blues Rock",
    "Blues Shouter",
    "British Blues",
    "Canadian Blues",
    "Chicago Blues",
    "Classic Blues",
    "Classic Female Blues",
    "Contemporary Blues",
    "Contemporary R&B",
    "Country Blues",
    "Dark Blues",
    "Delta Blues",
    "Detroit Blues",
    "Doom Blues",
    "Electric Blues",
    "Folk Blues",
    "Gospel Blues",
    "Harmonica Blues",
    "Hill Country Blues",
    "Hokum Blues",
    "Jazz Blues",
    "Jump Blues",
    "Kansas City Blues",
    "Louisiana Blues",
    "Memphis Blues",
    "Modern Blues",
    "New Orlean Blues",
    "NY Blues",
    "Piano Blues",
    "Piedmont Blues",
    "Punk Blues",
    "Ragtime Blues",
    "Rhythm Blues",
    "Soul Blues",
    "St. Louis Blues",
    "Swamp Blues",
    "Texas Blues",
    "Urban Blues",
    "Vandeville",
    "West Coast Blues",
    "Zydeco",
    // Children's Music
    "Children's Music",
    "Lullabies",
    "Sing-Along",
    "Stories",
    // Classical
    "Classical",
    "Avant-Garde",
    "Ballet",
    "Baroque",
    "Cantata",
    "Chamber Music",
    "String Quartet",
    "Chant",
    "Choral",
    "Classical Crossover",
    "Concerto",
    "Concerto Grosso",
    "Contemporary Classical",
    "Early Music",
    "Expressionist",
    "High Classical",
    "Impressionist",
    "Mass Requiem",
    "Medieval",
    "Minimalism",
    "Modern Composition",
    "Modern Classical",
    "Opera",
    "Oratorio",
    "Orchestral",
    "Organum",
    "Renaissance",
    "Romantic",
    "Sonata",
    "Symphonic",
    "Symphony",
    "Twelve-tone",
    "Wedding Music",
    // Comedy
    "Comedy",
    "Novelty",
    "Parody Music",
    "Stand-up Comedy",
    "Vaudeville",
    // Commercial
    "Commercial",
    "Jingles",
    "TV Themes",
    // Country
    "Country",
    "Alternative Country",
    "Americana",
    "Australian Country",
    "Bakersfield Sound",
    "Bluegrass",
    "Progressive Bluegrass",
    "Reactionary Bluegrass",
    "Blues Country",
    "Cajun Fiddle Tunes",
    "Christian Country",
    "Classic Country",
    "Close Harmony",
    "Contemporary Bluegrass",
    "Contemporary Country",
    "Country Gospel",
    "Country Pop",
    "Country Rap",
    "Country Rock",
    "Country Soul",
    "Cowboy",
    "Cowpunk",
    "Dansband",
    "Honky Tonk",
    "Franco-Country",
    "Gulf and Western",
    "Hellbilly Music",
    "Instrumental Country",
    "Lubbock Sound",
    "Nashville Sound",
    "Neotraditional Country",
    "Outlaw Country",
    "Progressive",
    "Psychobilly",
    "Red Dirt",
    "Sertanejo",
    "Texas County",
    "Traditional Bluegrass",
    "Traditional Country",
    "Truck-Driving Country",
    "Urban Cowboy",
    "Western Swing",
    // Dance (EDM)
    "Club",
    "Breakcore",
    "Breakbeat",
    "4-Beat",
    "Acid Breaks",
    "Baltimore Club",
    "Big Beat",
    "Breakbeat Hardcore",
    "Broken Beat",
    "Florida Breaks",
    "Nu Skool Breaks",
    "Brostep",
    "Chillstep",
    "Deep House",
    "Dubstep",
    "Electro House",
    "Electroswing",
    "Exercise",
    "Future Garage",
    "Garage",
    "Glitch Hop",
    "Glitch Pop",
    "Grime",
    "Hardcore",
    "Bouncy House",
    "Bouncy Techno",
    "Breakcore",
    "Digital Hardcore",
    "Doomcore",
    "Dubstyle",
    "Gabber",
    "Happy Hardcore",
    "Hardstyle",
    "Jumpstyle",
    "Makina",
    "Speedcore",
    "Terrorcore",
    "Uk Hardcore",
    "Hard Dance",
    "Hi-NRG",
    "Horrorcore",
    "House",
    "Acid House",
    "Chicago House",
    "Deep House",
    "Diva House",
    "Dutch House",
    "Electro House",
    "Freestyle House",
    "French House",
    "Funky House",
    "Ghetto House",
    "Hardbag",
    "Hip House",
    "Italo House",
    "Latin House",
    "Minimal House",
    "Progressive House",
    "Rave Music",
    "Swing House",
    "Tech House",
    "Tribal House",
    "Tropical House",
    "UK Hard House",
    "US Garage",
    "Vocal House",
    "Jackin House",
    "Jungle",
    "Liquid Dub",
    "Regstep",
    "Techno",
    "Acid Techno",
    "Detroit Techno",
    "Free Tekno",
    "Ghettotech",
    "Minimal",
    "Nortec",
    "Schranz",
    "Techno-Dnb",
    "Technopop",
    "Tecno Brega",
    "Toytown Techno",
    "Trance",
    "Acid Trance",
    "Classic Trance",
    "Dark Psy",
    "Deep House",
    "Dream Trance",
    "Goa Trance",
    "Dark Psytrance",
    "Full on",
    "Psybreaks",
    "Psyprog",
    "Suomisaundi",
    "Hard Trance",
    "Prog. Trance",
    "Psy-Trance",
    "Minimal Techno",
    "Tech House",
    "Tech Trance",
    "Uplifting Trance",
    "Orchestral Uplifting",
    "Vocal Trance",
    "Trap",
    // Disney
    "Disney",
    // Easy Listening
    "Easy Listening",
    "Background",
    "Bop",
    "Elevator",
    "Furniture",
    "Lounge",
    "Middle of the Road",
    "Swing",
    // Electronic
    "Electronic",
    "2-Step",
    "8bit",
    "Ambient",
    "Ambient Dub",
    "Ambient House",
    "Ambient Techno",
    "Dark Ambient",
    "Drone Music",
    "Illbient",
    "Isolationism",
    "Lowercase",
    "Asian Underground",
    "Bassline",
    "Chillwave",
    "Chiptune",
    "Crunk",
    "Downtempo",
    "Acid Jazz",
    "Balearic Beat",
    "Chill Out",
    "Dub Music",
    "Dubtronica",
    "Ethnic Electronica",
    "Moombahton",
    "Nu Jazz",
    "Trip Hop",
    "Drum & Bass",
    "Darkcore",
    "Darkstep",
    "Drumfunk",
    "Drumstep",
    "Hardstep",
    "Intelligent Drum and Bass",
    "Jump-Up",
    "Liquid Funk",
    "Neurofunk",
    "Oldschool Jungle",
    "Darkside Jungle",
    "Ragga Jungle",
    "Raggacore",
    "Sambass",
    "Techstep",
    "Electro",
    "Electro Backbeat",
    "Electro-Grime",
    "Electropop",
    "Electro-swing",
    "Electroacoustic",
    "Acousmatic Music",
    "Computer Music",
    "Electroacoustic Improvisation",
    "Field Recording",
    "Live Coding",
    "Live Electronics",
    "Soundscape Composition",
    "Tape Music",
    "Electronica",
    "Berlin School",
    "Electronic Art Music",
    "Electronic Dance Music",
    "Folktronica",
    "Freestyle Music",
    "Glitch",
    "Idm",
    "Laptronica",
    "Skweee",
    "Sound Art",
    "Synthcore",
    "Electronic Rock",
    "Alternative Dance",
    "Baggy",
    "Madchester",
    "Dance-Punk",
    "Dance-Rock",
    "Dark Wave",
    "Electroclash",
    "Electronicore",
    "Electropunk",
    "Ethereal Wave",
    "Indietronica",
    "New Rave",
    "Space Rock",
    "Synthpop",
    "Synthpunk",
    "Eurodance",
    "Bubblegum Dance",
    "Italo Dance",
    "Turbofolk",
    "Hardstyle",
    "Hi-Nrg",
    "Eurobeat",
    "Hard Nrg",
    "New Beat",
    "IDM/Experimental",
    "Industrial",
    "Trip Hop",
    "Vaporwave",
    "Hyponagogic",
    "Vektroid",
    "Mallsoft",
    "Vaportrap",
    "Vaporhop",
    "Protovapor",
    "UK Garage",
    "2-Step",
    "4×4",
    "Bassline",
    "Grime",
    "Speed Garage",
    // Inspirational
    "Inspirational",
    "Christian & Gospel",
    "CCM",
    "Christian Metal",
    "Christian Pop",
    "Christian Rap",
    "Christian Rock",
    "Classic Christian",
    "Contemporary Gospel",
    "Gospel",
    "Praise & Worship",
    "Qawwali",
    "Southern Gospel",
    "Traditional Gospel",
    // Instrumental
    "Instrumental",
    "March",
    // J-Pop
    "J-Rock",
    "J-Synth",
    "J-Ska",
    "J-Punk",
    // Jazz
    "Jazz",
    "Acid Jazz",
    "Afro-Cuban Jazz",
    "Avant-Garde Jazz",
    "Bebop",
    "Big Band",
    "Blue Note",
    "British Dance Band",
    "Cape Jazz",
    "Chamber Jazz",
    "Contemporary Jazz",
    "Continental Jazz",
    "Cool Jazz",
    "Crossover Jazz",
    "Dark Jazz",
    "Dixieland",
    "Early Jazz",
    "Electro Swing",
    "Ethio-jazz",
    "Ethno-Jazz",
    "European Free Jazz",
    "Free Funk",
    "Free Jazz",
    "Fusion",
    "Gypsy Jazz",
    "Hard Bop",
    "Indo Jazz",
    "Jazz Blues",
    "Jazz-Funk",
    "Jazz-Fusion",
    "Jazz Rap",
    "Jazz Rock",
    "Latin Jazz",
    "M-Base Jazz",
    "Mainstream Jazz",
    "Modal Jazz",
    "Neo-Bop",
    "Neo-Swing",
    "Nu Jazz",
    "Orchestral Jazz",
    "Post-Bop",
    "Punk Jazz",
    "Ragtime",
    "Ska Jazz",
    "Skiffle",
    "Smooth Jazz",
    "Soul Jazz",
    "Swing Jazz",
    "Straight-Ahead Jazz",
    "Trad Jazz",
    "Third Stream",
    "Jazz-Funk",
    "Free Jazz",
    "West Coast Jazz",
    // K-Pop
    "K-Pop",
    // Latin
    "Latin",
    "Alternativo & Rock Latino",
    "Argentine Tango",
    "Bachata",
    "Baithak Gana",
    "Baladas y Boleros",
    "Bolero",
    "Bossa Nova",
    "Brazilian",
    "Axé",
    "Bossa Nova",
    "Brazilian Rock",
    "Brega",
    "Choro",
    "Forró",
    "Frevo",
    "Funk Carioca",
    "Lambada",
    "Maracatu",
    "Música Popular Brasileira",
    "Música Sertaneja",
    "Pagode",
    "Samba",
    "Samba Rock",
    "Tecnobrega",
    "Tropicalia",
    "Zouk-Lambada",
    "Chicha",
    "Criolla",
    "Contemporary Latin",
    "Cumbia",
    "Flamenco",
    "Huayno",
    "Joropo",
    "Latin Jazz",
    "Mambo",
    "Mariachi",
    "Merengue Típico",
    "Nuevo Flamenco",
    "Pop Latino",
    "Portuguese Fado",
    "Punta",
    "Punta Rock",
    "Ranchera",
    "Raíces",
    "Raison",
    "Reggaeton y Hip-Hop",
    "Regional Mexicano",
    "Salsa y Tropical",
    "Soca",
    "Son",
    "Tejano",
    "Timba",
    "Twoubadou",
    "Vallenato",
    "Zouk",
    // Metal
    "Heavy Metal",
    "Speed Metal",
    "Thrash Metal",
    "Power Metal",
    "Death Metal",
    "Black Metal",
    "Pagan Metal",
    "Viking Metal",
    "Folk Metal",
    "Symphonic Metal",
    "Gothic Metal",
    "Glam Metal",
    "Hair Metal",
    "Doom Metal",
    "Groove Metal",
    "Industrial Metal",
    "Modern Metal",
    "Neoclassical Metal",
    "New Wave Of British Heavy Metal",
    "Post Metal",
    "Progressive Metal",
    "Avantgarde Metal",
    "Sludge",
    "Djent",
    "Drone",
    "Kawaii Metal",
    "Pirate Metal",
    "Nu Metal",
    "Neue Deutsche Härte",
    "Math Metal",
    "Crossover",
    "Grindcore",
    "Hardcore",
    "Metalcore",
    "Deathcore",
    "Post Hardcore",
    "Mathcore",
    // New Age
    "New Age",
    "Environmental",
    "Healing",
    "Meditation",
    "Nature",
    "Relaxation",
    "Travel",
    // Opera
    "Opera",
    // Pop
    "Pop",
    "Adult Contemporary",
    "Arab Pop",
    "Baroque",
    "Britpop",
    "Bubblegum Pop",
    "Chamber Pop",
    "Chanson",
    "Christian Pop",
    "Classical Crossover",
    "Europop",
    "Austropop",
    "Balkan Pop",
    "French Pop",
    "Latin Pop",
    "Laïkó",
    "Nederpop",
    "Russian Pop",
    "Dance Pop",
    "Dream Pop",
    "Electro Pop",
    "Iranian Pop",
    "Jangle Pop",
    "Latin Ballad",
    "Levenslied",
    "Louisiana Swamp Pop",
    "Mexican Pop",
    "Motorpop",
    "New Romanticism",
    "Orchestral Pop",
    "Pop Rap",
    "Popera",
    "Pop/Rock",
    "Pop Punk",
    "Power Pop",
    "Psychedelic Pop",
    "Schlager",
    "Soft Rock",
    "Sophisti-Pop",
    "Space Age Pop",
    "Sunshine Pop",
    "Surf Pop",
    "Synthpop",
    "Teen Pop",
    "Traditional Pop Music",
    "Turkish Pop",
    "Vispop",
    "Wonky Pop",
    "Post-Disco",
    "Boogie",
    "Dance-pop",
    "Progressive",
    "Progressive House",
    "Disco House",
    "Dream House",
    "Space House",
    "Japanese House",
    "Bounce",
    "Progressive Breaks",
    "Progressive Drum & Bass",
    "Progressive Techno",
    // R&B/Soul
    "R&B",
    "Soul",
    "(Carolina) Beach Music",
    "Contemporary R&B",
    "Disco",
    "Doo Wop",
    "Funk",
    "Modern Soul",
    "Motown",
    "Neo-Soul",
    "Northern Soul",
    "Psychedelic Soul",
    "Quiet Storm",
    "Soul",
    "Soul Blues",
    "Southern Soul",
    // Reggae
    "Reggae",
    "2-Tone",
    "Dub",
    "Roots Reggae",
    "Reggae Fusion",
    "Reggae en Español",
    "Spanish Reggae",
    "Reggae 110",
    "Reggae Bultrón",
    "Romantic Flow",
    "Lovers Rock",
    "Raggamuffin",
    "Ragga",
    "Dancehall",
    "Ska",
    // Rock
    "Rock",
    "Acid Rock",
    "Adult-Oriented Rock",
    "Afro Punk",
    "Adult Alternative",
    "American Traditional Rock",
    "Anatolian Rock",
    "Arena Rock",
    "Art Rock",
    "Blues-Rock",
    "British Invasion",
    "Cock Rock",
    "Death Metal",
    "Doom Metal",
    "Glam Rock",
    "Gothic Metal",
    "Grind Core",
    "Hair Metal",
    "Hard Rock",
    "Math Metal",
    "Math Rock",
    "Metal",
    "Metal Core",
    "Noise Rock",
    "Jam Bands",
    "Post Punk",
    "Post Rock",
    "Prog-Rock/Art Rock",
    "Progressive Metal",
    "Psychedelic",
    "Rock & Roll",
    "Rockabilly",
    "Roots Rock",
    "Singer/Songwriter",
    "Southern Rock",
    "Spazzcore",
    "Stoner Metal",
    "Surf",
    "Technical Death Metal",
    "Tex-Mex",
    "Thrash Metal",
    "Time Lord Rock",
    "Trip-hop",
    "Yacht Rock",
    // Singer/Songwriter
    "Alternative Folk",
    "Contemporary Folk",
    "Contemporary Singer/Songwriter",
    "Indie Folk",
    "Folk-Rock",
    "Love Song",
    "New Acoustic",
    "Traditional Folk",
    // Soundtrack
    "Soundtrack",
    "Foreign Cinema",
    "Movie Soundtrack",
    "Musicals",
    "Original Score",
    "TV Soundtrack",
    // Spoken Word
    "Spoken Word",
    // Tex-Mex / Tejano
    "Chicano",
    "Classic",
    "Conjunto",
    "Conjunto Progressive",
    "New Mex",
    "Tex-Mex",
    // Vocal
    "A cappella",
    "Barbershop",
    "Cantique",
    "Doo-wop",
    "Gregorian Chant",
    "Standards",
    "Traditional Pop",
    "Vocal Jazz",
    "Vocal Pop",
    "Yodel",
    // World
    "World",
    "Africa",
    "African Heavy Metal",
    "African Hip Hop",
    "Afro-Beat",
    "Afro-House",
    "Afro-Pop",
    "Apala",
    "Benga",
    "Bikutsi",
    "Bongo Flava",
    "Cape Jazz",
    "Chimurenga",
    "Coupé-Décalé",
    "Fuji Music",
    "Genge",
    "Gnawa",
    "Highlife",
    "Hiplife",
    "Isicathamiya",
    "Jit",
    "Jùjú",
    "Kapuka",
    "Kizomba",
    "Kuduro",
    "Kwaito",
    "Kwela",
    "Lingala",
    "Makossa",
    "Maloya",
    "Marrabenta",
    "Mbalax",
    "Mbaqanga",
    "Mbube",
    "Morna",
    "Museve",
    "Negro Spiritual",
    "Palm-Wine",
    "Raï",
    "Sakara",
    "Sega",
    "Seggae",
    "Semba",
    "Soukous",
    "Taarab",
    "Zouglou",
    "Asia",
    "Anison",
    "Baithak Gana",
    "C-Pop",
    "CityPop",
    "Cantopop",
    "Enka",
    "Hong Kong English Pop",
    "Fann At-Tanbura",
    "Fijiri",
    "J-Pop",
    "K-Pop",
    "Karaoke",
    "Kayōkyoku",
    "Lao-Hmong",
    "Mandopop",
    "Manila Sound",
    "Mizrahi",
    "Morlam",
    "Music of the Philippines",
    "Mbalax",
    "Nhạc trẻ",
    "Nueva Cancion",
    "O-Pop",
    "Onkyokei",
    "Original Pilipino Music",
    "Pinoy pop",
    "Pop sunda",
    "Qawwali",
    "Qasidah",
    "Qasidah Modern",
    "Qasidah Sholawat",
    "Qasidah Melayu",
    "Qasidah Nasid",
    "Qasidah Gambus",
    "Ragini",
    "Raga",
    "Rai",
    "Sholawat",
    "Tapanuli",
    "Thai pop",
    "Tongan pop",
    "World Fusion",
    "Zouk",
    // Others
    "Holiday",
    "Chanukah",
    "Christmas",
    "Christmas Crossover",
    "Christmas Gospel",
    "Easter",
    "Halloween",
    "Holiday",
    "Chanukah",
    "Christmas",
    "Christmas Crossover",
    "Christmas Gospel",
    "Easter",
    "Halloween",
    "Holiday",
    "Chanukah",
    "Christmas",
    "Christmas Crossover",
    "Christmas Gospel",
    "Easter",
    "Halloween",
    "Thanksgiving",
];
